import { Trip, ChecklistItem } from '../models/trip.models';

// ---------------------------------------------------------------------------
// Rule interface
// ---------------------------------------------------------------------------

export interface ChecklistRule {
  id: string;
  condition: (trip: Trip) => boolean;
  generate: (trip: Trip) => Omit<ChecklistItem, 'id' | 'isChecked' | 'autoGenerated'>[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Add (or subtract) `days` from a YYYY-MM-DD date string. Returns YYYY-MM-DD. */
export function addDays(dateStr: string, days: number): string {
  const d = new Date(dateStr + 'T00:00:00');
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

/** Number of days between two YYYY-MM-DD dates (inclusive count - 1). */
function daysBetween(start: string, end: string): number {
  const s = new Date(start + 'T00:00:00').getTime();
  const e = new Date(end + 'T00:00:00').getTime();
  return Math.round((e - s) / (1000 * 60 * 60 * 24));
}

// Common Brazilian cities for the international heuristic
const BRAZILIAN_CITIES = [
  'sao paulo',
  'são paulo',
  'rio de janeiro',
  'brasilia',
  'brasília',
  'salvador',
  'fortaleza',
  'belo horizonte',
  'manaus',
  'curitiba',
  'recife',
  'porto alegre',
  'belem',
  'belém',
  'goiania',
  'goiânia',
  'guarulhos',
  'campinas',
  'florianopolis',
  'florianópolis',
  'natal',
  'maceio',
  'maceió',
  'vitoria',
  'vitória',
  'foz do iguacu',
  'foz do iguaçu',
  'gramado',
  'buzios',
  'búzios',
  'paraty',
  'parati',
  'campos do jordao',
  'campos do jordão',
  'joao pessoa',
  'joão pessoa',
  'aracaju',
  'cuiaba',
  'cuiabá',
  'teresina',
  'sao luis',
  'são luís',
  'fernando de noronha',
  'chapada diamantina',
  'lencois maranhenses',
  'lençóis maranhenses',
  'bonito',
  'jericoacoara',
  'brasil',
  'brazil',
];

/**
 * Simple heuristic: returns true if the destination likely is NOT a
 * Brazilian city/destination.
 */
export function isInternational(destination: string): boolean {
  const lower = destination.toLowerCase().trim();
  return !BRAZILIAN_CITIES.some((city) => lower.includes(city));
}

// ---------------------------------------------------------------------------
// Rules
// ---------------------------------------------------------------------------

export const RULES: ChecklistRule[] = [
  // 1. International travel documents
  {
    id: 'international-docs',
    condition: (trip) => isInternational(trip.destination),
    generate: (trip) => {
      const start = trip.dates.start;
      return [
        {
          ruleId: 'international-docs',
          label: 'Verificar validade do passaporte (minimo 6 meses)',
          dueDate: addDays(start, -90),
          category: 'documents',
          priority: 'high',
        },
        {
          ruleId: 'international-docs',
          label: 'Verificar necessidade de visto',
          dueDate: addDays(start, -60),
          category: 'documents',
          priority: 'high',
        },
        {
          ruleId: 'international-docs',
          label: 'Contratar seguro viagem internacional',
          dueDate: addDays(start, -30),
          category: 'documents',
          priority: 'high',
        },
        {
          ruleId: 'international-docs',
          label: 'Solicitar cartao internacional ou conta global',
          dueDate: addDays(start, -7),
          category: 'finance',
          priority: 'high',
        },
      ];
    },
  },

  // 2. Flights
  {
    id: 'has-flights',
    condition: (trip) => trip.flights.length > 0,
    generate: (trip) => {
      const start = trip.dates.start;
      return [
        {
          ruleId: 'has-flights',
          label: 'Fazer check-in online',
          dueDate: addDays(start, -1),
          category: 'logistics',
          priority: 'high',
        },
        {
          ruleId: 'has-flights',
          label: 'Salvar cartoes de embarque no celular',
          dueDate: addDays(start, -1),
          category: 'documents',
          priority: 'high',
        },
        {
          ruleId: 'has-flights',
          label: 'Conferir limites de bagagem da companhia',
          dueDate: addDays(start, -3),
          category: 'packing',
          priority: 'medium',
        },
      ];
    },
  },

  // 3. Hotel / Stays
  {
    id: 'has-stays',
    condition: (trip) => trip.stays.length > 0,
    generate: (trip) => {
      const start = trip.dates.start;
      return [
        {
          ruleId: 'has-stays',
          label: 'Imprimir ou salvar confirmacao da reserva do hotel',
          dueDate: addDays(start, -3),
          category: 'documents',
          priority: 'medium',
        },
        {
          ruleId: 'has-stays',
          label: 'Confirmar horario de check-in com o hotel',
          dueDate: addDays(start, -1),
          category: 'logistics',
          priority: 'medium',
        },
      ];
    },
  },

  // 4. Car rentals
  {
    id: 'has-car',
    condition: (trip) => trip.carRentals.length > 0,
    generate: (trip) => {
      const start = trip.dates.start;
      return [
        {
          ruleId: 'has-car',
          label: 'Verificar CNH valida ou PID (Permissao Internacional para Dirigir)',
          dueDate: addDays(start, -30),
          category: 'documents',
          priority: 'high',
        },
        {
          ruleId: 'has-car',
          label: 'Garantir cartao de credito para caucao da locadora',
          dueDate: addDays(start, -7),
          category: 'finance',
          priority: 'medium',
        },
      ];
    },
  },

  // 5. Long trip (> 7 days)
  {
    id: 'long-trip',
    condition: (trip) => daysBetween(trip.dates.start, trip.dates.end) > 7,
    generate: (trip) => {
      const start = trip.dates.start;
      return [
        {
          ruleId: 'long-trip',
          label: 'Preparar kit de lavanderia (sabao portatil, varal retratil)',
          dueDate: addDays(start, -5),
          category: 'packing',
          priority: 'low',
        },
        {
          ruleId: 'long-trip',
          label: 'Montar kit de primeiros socorros',
          dueDate: addDays(start, -5),
          category: 'health',
          priority: 'medium',
        },
      ];
    },
  },

  // 6. General (always applies)
  {
    id: 'general',
    condition: () => true,
    generate: (trip) => {
      const start = trip.dates.start;
      return [
        {
          ruleId: 'general',
          label: 'Fazer as malas',
          dueDate: addDays(start, -2),
          category: 'packing',
          priority: 'high',
        },
        {
          ruleId: 'general',
          label: 'Avisar banco sobre viagem para evitar bloqueio do cartao',
          dueDate: addDays(start, -7),
          category: 'finance',
          priority: 'medium',
        },
        {
          ruleId: 'general',
          label: 'Confirmar transfer para o aeroporto',
          dueDate: addDays(start, -3),
          category: 'logistics',
          priority: 'medium',
        },
      ];
    },
  },
];

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Generate a merged checklist by running all applicable rules against the
 * trip.  Items already present in `existingItems` (matched by ruleId + label)
 * are kept as-is; only genuinely new items are appended.
 */
export function generateChecklist(
  trip: Trip,
  existingItems: ChecklistItem[],
): ChecklistItem[] {
  const existingKeys = new Set(
    existingItems.map((item) => `${item.ruleId}::${item.label}`),
  );

  const newItems: ChecklistItem[] = [];

  for (const rule of RULES) {
    if (!rule.condition(trip)) continue;

    const generated = rule.generate(trip);

    for (const partial of generated) {
      const key = `${partial.ruleId}::${partial.label}`;
      if (existingKeys.has(key)) continue;

      newItems.push({
        id: crypto.randomUUID(),
        isChecked: false,
        autoGenerated: true,
        ...partial,
      });
      existingKeys.add(key); // prevent duplicates within the same generation pass
    }
  }

  return [...existingItems, ...newItems];
}
