// Mock data for development — domain model format (same as Angular's domain models)
// When MOCK_MODE=true, backend returns this data directly with { _mock: true, data: [...] }
// Angular services detect _mock flag and skip external API mappers

// ─── Destination Images ───────────────────────────────────────────────────────
// Maps IATA codes to destination photos. Add new entries as the database grows.
// Images sourced from Unsplash (free, high-quality, stable URLs).

export const DESTINATION_IMAGES: Record<string, { url: string; credit: string }> = {
  // Brasil - Capitais & Destinos Turísticos
  GIG: { url: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80', credit: 'Agustin Diaz Gargiulo' },
  GRU: { url: 'https://images.unsplash.com/photo-1554168848-228452c09d60?auto=format&fit=crop&w=800&q=80', credit: 'Joao Tzanno' },
  SSA: { url: 'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?auto=format&fit=crop&w=800&q=80', credit: 'Isha Dias' },
  REC: { url: 'https://images.unsplash.com/photo-1598301257982-0cf014dabbcd?auto=format&fit=crop&w=800&q=80', credit: 'Edson Rosas' },
  FOR: { url: 'https://images.unsplash.com/photo-1629978658579-4bfb5019a5a1?auto=format&fit=crop&w=800&q=80', credit: 'Iana Dmytrenko' },
  NAT: { url: 'https://images.unsplash.com/photo-1614359291877-7f15e286e021?auto=format&fit=crop&w=800&q=80', credit: 'Helio Dilolwa' },
  FLN: { url: 'https://images.unsplash.com/photo-1588001832198-c15cff59b078?auto=format&fit=crop&w=800&q=80', credit: 'Eduardo Moody' },
  CWB: { url: 'https://images.unsplash.com/photo-1586968820004-59bc1e2f40b9?auto=format&fit=crop&w=800&q=80', credit: 'Marcos Paulo' },
  BSB: { url: 'https://images.unsplash.com/photo-1593194012930-e1684bcc002b?auto=format&fit=crop&w=800&q=80', credit: 'Luisa Meyberg' },
  CNF: { url: 'https://images.unsplash.com/photo-1599069488237-d62cf252b0ee?auto=format&fit=crop&w=800&q=80', credit: 'Fabrizio Velez' },
  POA: { url: 'https://images.unsplash.com/photo-1591107747893-1a09fbe0ae2d?auto=format&fit=crop&w=800&q=80', credit: 'Julio Flores' },
  MCZ: { url: 'https://images.unsplash.com/photo-1624117186803-0b62c8e0e5b3?auto=format&fit=crop&w=800&q=80', credit: 'Leandro Matos' },
  MAO: { url: 'https://images.unsplash.com/photo-1611508644466-8f805416d74a?auto=format&fit=crop&w=800&q=80', credit: 'Marcus Dall Col' },
  BEL: { url: 'https://images.unsplash.com/photo-1622997474084-aa56e1af4021?auto=format&fit=crop&w=800&q=80', credit: 'Rui Silvestre' },
  // Internacional
  LIS: { url: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?auto=format&fit=crop&w=800&q=80', credit: 'Daniel Seßler' },
  CDG: { url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80', credit: 'Chris Karidis' },
  FCO: { url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80', credit: 'David Köhler' },
  EZE: { url: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80', credit: 'Barbara Zandoval' },
  SCL: { url: 'https://images.unsplash.com/photo-1510272839903-3c67b46ee68d?auto=format&fit=crop&w=800&q=80', credit: 'Pablo Garcia' },
  MIA: { url: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?auto=format&fit=crop&w=800&q=80', credit: 'Ryan Parker' },
  JFK: { url: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80', credit: 'Oliver Niblett' },
  LHR: { url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80', credit: 'Benjamin Davies' },
  MAD: { url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=80', credit: 'Florian Wehde' },
  BOG: { url: 'https://images.unsplash.com/photo-1568632234157-ce7aecd03d0d?auto=format&fit=crop&w=800&q=80', credit: 'Flavia Carpio' },
  MEX: { url: 'https://images.unsplash.com/photo-1518659526054-190340b32735?auto=format&fit=crop&w=800&q=80', credit: 'Jezael Melgoza' },
};

// ─── Airports ──────────────────────────────────────────────────────────────────

export const MOCK_AIRPORTS = [
  { iataCode: 'GRU', name: 'Guarulhos International', cityName: 'São Paulo' },
  { iataCode: 'CGH', name: 'Congonhas', cityName: 'São Paulo' },
  { iataCode: 'VCP', name: 'Viracopos', cityName: 'Campinas' },
  { iataCode: 'GIG', name: 'Galeão - Tom Jobim', cityName: 'Rio de Janeiro' },
  { iataCode: 'SDU', name: 'Santos Dumont', cityName: 'Rio de Janeiro' },
  { iataCode: 'BSB', name: 'Presidente Juscelino Kubitschek', cityName: 'Brasília' },
  { iataCode: 'CNF', name: 'Tancredo Neves / Confins', cityName: 'Belo Horizonte' },
  { iataCode: 'SSA', name: 'Deputado Luís Eduardo Magalhães', cityName: 'Salvador' },
  { iataCode: 'REC', name: 'Guararapes - Gilberto Freyre', cityName: 'Recife' },
  { iataCode: 'POA', name: 'Salgado Filho', cityName: 'Porto Alegre' },
  { iataCode: 'CWB', name: 'Afonso Pena', cityName: 'Curitiba' },
  { iataCode: 'FOR', name: 'Pinto Martins', cityName: 'Fortaleza' },
  { iataCode: 'MAO', name: 'Eduardo Gomes', cityName: 'Manaus' },
  { iataCode: 'FLN', name: 'Hercílio Luz', cityName: 'Florianópolis' },
  { iataCode: 'NAT', name: 'São Gonçalo do Amarante', cityName: 'Natal' },
  { iataCode: 'BEL', name: 'Val de Cans', cityName: 'Belém' },
  { iataCode: 'MCZ', name: 'Zumbi dos Palmares', cityName: 'Maceió' },
  { iataCode: 'CGB', name: 'Marechal Rondon', cityName: 'Cuiabá' },
  { iataCode: 'GYN', name: 'Santa Genoveva', cityName: 'Goiânia' },
  { iataCode: 'LIS', name: 'Humberto Delgado', cityName: 'Lisboa' },
  { iataCode: 'CDG', name: 'Charles de Gaulle', cityName: 'Paris' },
  { iataCode: 'JFK', name: 'John F. Kennedy', cityName: 'Nova York' },
  { iataCode: 'MIA', name: 'Miami International', cityName: 'Miami' },
  { iataCode: 'EZE', name: 'Ministro Pistarini', cityName: 'Buenos Aires' },
  { iataCode: 'SCL', name: 'Arturo Merino Benítez', cityName: 'Santiago' },
  { iataCode: 'BOG', name: 'El Dorado', cityName: 'Bogotá' },
  { iataCode: 'MEX', name: 'Benito Juárez', cityName: 'Cidade do México' },
  { iataCode: 'FCO', name: 'Leonardo da Vinci - Fiumicino', cityName: 'Roma' },
  { iataCode: 'LHR', name: 'Heathrow', cityName: 'Londres' },
  { iataCode: 'MAD', name: 'Adolfo Suárez Madrid-Barajas', cityName: 'Madrid' },
];

// ─── Flights ───────────────────────────────────────────────────────────────────

export const MOCK_FLIGHTS = [
  {
    id: 'fl-001', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'GIG',
    departureAt: '2026-03-15T08:30:00', arrivalAt: '2026-03-15T09:40:00',
    airline: 'LATAM', flightNumber: 'LA3021', durationMinutes: 70, stops: 0,
    price: { total: 389.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'fl-002', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'GIG',
    departureAt: '2026-03-15T10:15:00', arrivalAt: '2026-03-15T11:20:00',
    airline: 'GOL', flightNumber: 'G3 1102', durationMinutes: 65, stops: 0,
    price: { total: 329.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
  {
    id: 'fl-003', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'GIG',
    departureAt: '2026-03-15T14:00:00', arrivalAt: '2026-03-15T15:10:00',
    airline: 'Azul', flightNumber: 'AD 4112', durationMinutes: 70, stops: 0,
    price: { total: 349.50, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
  },
  {
    id: 'fl-004', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'SSA',
    departureAt: '2026-03-15T07:00:00', arrivalAt: '2026-03-15T09:30:00',
    airline: 'LATAM', flightNumber: 'LA3401', durationMinutes: 150, stops: 0,
    price: { total: 649.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'fl-005', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'SSA',
    departureAt: '2026-03-15T11:30:00', arrivalAt: '2026-03-15T15:45:00',
    airline: 'GOL', flightNumber: 'G3 1520', durationMinutes: 255, stops: 1,
    price: { total: 479.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
  {
    id: 'fl-006', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'REC',
    departureAt: '2026-03-15T06:45:00', arrivalAt: '2026-03-15T10:00:00',
    airline: 'Azul', flightNumber: 'AD 2740', durationMinutes: 195, stops: 0,
    price: { total: 599.00, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
  },
  {
    id: 'fl-007', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'FOR',
    departureAt: '2026-03-15T09:15:00', arrivalAt: '2026-03-15T12:50:00',
    airline: 'LATAM', flightNumber: 'LA3155', durationMinutes: 215, stops: 0,
    price: { total: 719.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'fl-008', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'LIS',
    departureAt: '2026-03-15T22:00:00', arrivalAt: '2026-03-16T10:30:00',
    airline: 'LATAM', flightNumber: 'LA8084', durationMinutes: 570, stops: 0,
    price: { total: 3249.00, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'fl-009', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'MIA',
    departureAt: '2026-03-15T23:30:00', arrivalAt: '2026-03-16T06:15:00',
    airline: 'GOL', flightNumber: 'G3 8701', durationMinutes: 525, stops: 0,
    price: { total: 2890.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
  {
    id: 'fl-010', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'EZE',
    departureAt: '2026-03-15T08:00:00', arrivalAt: '2026-03-15T11:30:00',
    airline: 'Azul', flightNumber: 'AD 8502', durationMinutes: 210, stops: 0,
    price: { total: 1450.00, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
  },
];

// ─── Flight Showcase ──────────────────────────────────────────────────────────
// Pre-curated data for the public flights showcase page (3 sections × 6 items)

export const MOCK_SHOWCASE_DEALS = [
  {
    id: 'sd-001', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'GIG', originCity: 'São Paulo', destinationCity: 'Rio de Janeiro',
    departureAt: '2026-04-10T10:15:00', arrivalAt: '2026-04-10T11:20:00',
    airline: 'GOL', flightNumber: 'G3 1102', durationMinutes: 65, stops: 0,
    price: { total: 189.90, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
  {
    id: 'sd-002', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'CWB', originCity: 'São Paulo', destinationCity: 'Curitiba',
    departureAt: '2026-04-12T06:30:00', arrivalAt: '2026-04-12T07:40:00',
    airline: 'Azul', flightNumber: 'AD 4508', durationMinutes: 70, stops: 0,
    price: { total: 199.00, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
  },
  {
    id: 'sd-003', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'CNF', originCity: 'São Paulo', destinationCity: 'Belo Horizonte',
    departureAt: '2026-04-15T08:00:00', arrivalAt: '2026-04-15T09:10:00',
    airline: 'LATAM', flightNumber: 'LA3250', durationMinutes: 70, stops: 0,
    price: { total: 219.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'sd-004', source: 'mock', addedToItinerary: false,
    origin: 'GIG', destination: 'SSA', originCity: 'Rio de Janeiro', destinationCity: 'Salvador',
    departureAt: '2026-04-18T11:30:00', arrivalAt: '2026-04-18T13:50:00',
    airline: 'GOL', flightNumber: 'G3 1415', durationMinutes: 140, stops: 0,
    price: { total: 249.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
  {
    id: 'sd-005', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'POA', originCity: 'São Paulo', destinationCity: 'Porto Alegre',
    departureAt: '2026-04-20T14:00:00', arrivalAt: '2026-04-20T15:40:00',
    airline: 'Azul', flightNumber: 'AD 2810', durationMinutes: 100, stops: 0,
    price: { total: 269.50, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
  },
  {
    id: 'sd-006', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'BSB', originCity: 'São Paulo', destinationCity: 'Brasília',
    departureAt: '2026-04-22T07:00:00', arrivalAt: '2026-04-22T08:45:00',
    airline: 'LATAM', flightNumber: 'LA3080', durationMinutes: 105, stops: 0,
    price: { total: 279.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
];

export const MOCK_SHOWCASE_POPULAR = [
  {
    id: 'sp-001', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'SSA', originCity: 'São Paulo', destinationCity: 'Salvador',
    departureAt: '2026-04-10T07:00:00', arrivalAt: '2026-04-10T09:30:00',
    airline: 'LATAM', flightNumber: 'LA3401', durationMinutes: 150, stops: 0,
    price: { total: 549.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
    popularity: 98,
  },
  {
    id: 'sp-002', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'REC', originCity: 'São Paulo', destinationCity: 'Recife',
    departureAt: '2026-04-12T06:45:00', arrivalAt: '2026-04-12T10:00:00',
    airline: 'Azul', flightNumber: 'AD 2740', durationMinutes: 195, stops: 0,
    price: { total: 499.00, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
    popularity: 95,
  },
  {
    id: 'sp-003', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'FOR', originCity: 'São Paulo', destinationCity: 'Fortaleza',
    departureAt: '2026-04-14T09:15:00', arrivalAt: '2026-04-14T12:50:00',
    airline: 'GOL', flightNumber: 'G3 1520', durationMinutes: 215, stops: 0,
    price: { total: 579.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
    popularity: 92,
  },
  {
    id: 'sp-004', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'NAT', originCity: 'São Paulo', destinationCity: 'Natal',
    departureAt: '2026-04-16T08:00:00', arrivalAt: '2026-04-16T11:40:00',
    airline: 'LATAM', flightNumber: 'LA3480', durationMinutes: 220, stops: 0,
    price: { total: 619.90, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
    popularity: 89,
  },
  {
    id: 'sp-005', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'MCZ', originCity: 'São Paulo', destinationCity: 'Maceió',
    departureAt: '2026-04-18T10:30:00', arrivalAt: '2026-04-18T14:00:00',
    airline: 'Azul', flightNumber: 'AD 2900', durationMinutes: 210, stops: 0,
    price: { total: 529.00, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
    popularity: 87,
  },
  {
    id: 'sp-006', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'FLN', originCity: 'São Paulo', destinationCity: 'Florianópolis',
    departureAt: '2026-04-20T15:00:00', arrivalAt: '2026-04-20T16:15:00',
    airline: 'GOL', flightNumber: 'G3 1085', durationMinutes: 75, stops: 0,
    price: { total: 389.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
    popularity: 85,
  },
];

export const MOCK_SHOWCASE_RECOMMENDED = [
  {
    id: 'sr-001', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'LIS', originCity: 'São Paulo', destinationCity: 'Lisboa',
    departureAt: '2026-05-01T22:00:00', arrivalAt: '2026-05-02T10:30:00',
    airline: 'LATAM', flightNumber: 'LA8084', durationMinutes: 570, stops: 0,
    price: { total: 2849.00, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'sr-002', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'CDG', originCity: 'São Paulo', destinationCity: 'Paris',
    departureAt: '2026-05-05T21:30:00', arrivalAt: '2026-05-06T13:10:00',
    airline: 'LATAM', flightNumber: 'LA8040', durationMinutes: 640, stops: 0,
    price: { total: 3190.00, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'sr-003', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'FCO', originCity: 'São Paulo', destinationCity: 'Roma',
    departureAt: '2026-05-10T23:00:00', arrivalAt: '2026-05-11T14:20:00',
    airline: 'Azul', flightNumber: 'AD 9070', durationMinutes: 680, stops: 0,
    price: { total: 3350.00, currency: 'BRL' },
    link: { url: 'https://www.voeazul.com.br', provider: 'Azul' },
  },
  {
    id: 'sr-004', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'EZE', originCity: 'São Paulo', destinationCity: 'Buenos Aires',
    departureAt: '2026-05-08T08:00:00', arrivalAt: '2026-05-08T11:30:00',
    airline: 'GOL', flightNumber: 'G3 8702', durationMinutes: 210, stops: 0,
    price: { total: 1290.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
  {
    id: 'sr-005', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'SCL', originCity: 'São Paulo', destinationCity: 'Santiago',
    departureAt: '2026-05-12T09:30:00', arrivalAt: '2026-05-12T13:50:00',
    airline: 'LATAM', flightNumber: 'LA8140', durationMinutes: 260, stops: 0,
    price: { total: 1450.00, currency: 'BRL' },
    link: { url: 'https://www.latam.com', provider: 'LATAM' },
  },
  {
    id: 'sr-006', source: 'mock', addedToItinerary: false,
    origin: 'GRU', destination: 'MIA', originCity: 'São Paulo', destinationCity: 'Miami',
    departureAt: '2026-05-15T23:30:00', arrivalAt: '2026-05-16T06:15:00',
    airline: 'GOL', flightNumber: 'G3 8701', durationMinutes: 525, stops: 0,
    price: { total: 2690.00, currency: 'BRL' },
    link: { url: 'https://www.voegol.com.br', provider: 'GOL' },
  },
];

// ─── City Images (for Hotels / Tours) ─────────────────────────────────────────
// Maps city names to photos. Reuses Unsplash URLs where available.

export const CITY_IMAGES: Record<string, { url: string; credit: string }> = {
  'Rio de Janeiro': { url: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80', credit: 'Agustin Diaz Gargiulo' },
  'São Paulo': { url: 'https://images.unsplash.com/photo-1554168848-228452c09d60?auto=format&fit=crop&w=800&q=80', credit: 'Joao Tzanno' },
  'Salvador': { url: 'https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?auto=format&fit=crop&w=800&q=80', credit: 'Isha Dias' },
  'Recife': { url: 'https://images.unsplash.com/photo-1598301257982-0cf014dabbcd?auto=format&fit=crop&w=800&q=80', credit: 'Edson Rosas' },
  'Fortaleza': { url: 'https://images.unsplash.com/photo-1629978658579-4bfb5019a5a1?auto=format&fit=crop&w=800&q=80', credit: 'Iana Dmytrenko' },
  'Natal': { url: 'https://images.unsplash.com/photo-1614359291877-7f15e286e021?auto=format&fit=crop&w=800&q=80', credit: 'Helio Dilolwa' },
  'Florianópolis': { url: 'https://images.unsplash.com/photo-1588001832198-c15cff59b078?auto=format&fit=crop&w=800&q=80', credit: 'Eduardo Moody' },
  'Curitiba': { url: 'https://images.unsplash.com/photo-1586968820004-59bc1e2f40b9?auto=format&fit=crop&w=800&q=80', credit: 'Marcos Paulo' },
  'Brasília': { url: 'https://images.unsplash.com/photo-1593194012930-e1684bcc002b?auto=format&fit=crop&w=800&q=80', credit: 'Luisa Meyberg' },
  'Belo Horizonte': { url: 'https://images.unsplash.com/photo-1599069488237-d62cf252b0ee?auto=format&fit=crop&w=800&q=80', credit: 'Fabrizio Velez' },
  'Porto Alegre': { url: 'https://images.unsplash.com/photo-1591107747893-1a09fbe0ae2d?auto=format&fit=crop&w=800&q=80', credit: 'Julio Flores' },
  'Maceió': { url: 'https://images.unsplash.com/photo-1624117186803-0b62c8e0e5b3?auto=format&fit=crop&w=800&q=80', credit: 'Leandro Matos' },
  'Manaus': { url: 'https://images.unsplash.com/photo-1611508644466-8f805416d74a?auto=format&fit=crop&w=800&q=80', credit: 'Marcus Dall Col' },
  'Belém': { url: 'https://images.unsplash.com/photo-1622997474084-aa56e1af4021?auto=format&fit=crop&w=800&q=80', credit: 'Rui Silvestre' },
  'Lisboa': { url: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?auto=format&fit=crop&w=800&q=80', credit: 'Daniel Seßler' },
  'Paris': { url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80', credit: 'Chris Karidis' },
  'Roma': { url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80', credit: 'David Köhler' },
  'Buenos Aires': { url: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80', credit: 'Barbara Zandoval' },
  'Santiago': { url: 'https://images.unsplash.com/photo-1510272839903-3c67b46ee68d?auto=format&fit=crop&w=800&q=80', credit: 'Pablo Garcia' },
  'Gramado': { url: 'https://images.unsplash.com/photo-1609942072796-a1e1031a5b5a?auto=format&fit=crop&w=800&q=80', credit: 'Anderson Schmig' },
  'Jericoacoara': { url: 'https://images.unsplash.com/photo-1598977054780-5646a76fc498?auto=format&fit=crop&w=800&q=80', credit: 'Gustavo Ferreira' },
  'Paraty': { url: 'https://images.unsplash.com/photo-1599505037204-f2828c30b0a1?auto=format&fit=crop&w=800&q=80', credit: 'Bianca Fazacas' },
  'Fernando de Noronha': { url: 'https://images.unsplash.com/photo-1596394723269-e1e8e1cd3e9a?auto=format&fit=crop&w=800&q=80', credit: 'Edson Junior' },
  'Búzios': { url: 'https://images.unsplash.com/photo-1591017403286-fd8493524e1e?auto=format&fit=crop&w=800&q=80', credit: 'Evgeniy Alyoshin' },
  'Foz do Iguaçu': { url: 'https://images.unsplash.com/photo-1542704792-e30de8026022?auto=format&fit=crop&w=800&q=80', credit: 'Derek Oyen' },
  'Bonito': { url: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=800&q=80', credit: 'Jefferson Reis' },
  'Chapada Diamantina': { url: 'https://images.unsplash.com/photo-1591019479261-1a103585c559?auto=format&fit=crop&w=800&q=80', credit: 'Pedro Menezes' },
};

// ─── Hotel Showcase ───────────────────────────────────────────────────────────
// Pre-curated data for the public hotels showcase page (3 sections × 6 items)

export const MOCK_HOTEL_SHOWCASE_BEST_PRICES = [
  {
    id: 'hsp-001', source: 'mock',
    name: 'Ibis Copacabana Posto 2',
    city: 'Rio de Janeiro',
    address: 'Rua Min. Viveiros de Castro, 134 - Copacabana',
    type: 'Hotel',
    rating: 3.8, reviewCount: 1245,
    pricePerNight: { total: 195.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsp1/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsp-002', source: 'mock',
    name: 'Hotel Express Vieiralves',
    city: 'Manaus',
    address: 'Rua Rio Jutaí, 1192 - Vieiralves',
    type: 'Hotel',
    rating: 4.0, reviewCount: 820,
    pricePerNight: { total: 169.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsp2/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsp-003', source: 'mock',
    name: 'Pousada Maravilha do Cerrado',
    city: 'Brasília',
    address: 'SHN Quadra 2, Bloco F',
    type: 'Pousada',
    rating: 4.1, reviewCount: 456,
    pricePerNight: { total: 149.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsp3/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsp-004', source: 'mock',
    name: 'Selina Lapa',
    city: 'Rio de Janeiro',
    address: 'R. do Riachuelo, 169 - Lapa',
    type: 'Hostel',
    rating: 4.0, reviewCount: 987,
    pricePerNight: { total: 120.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsp4/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsp-005', source: 'mock',
    name: 'Hotel Slaviero Salvador',
    city: 'Salvador',
    address: 'Av. Sete de Setembro, 2009 - Vitória',
    type: 'Hotel',
    rating: 4.2, reviewCount: 678,
    pricePerNight: { total: 189.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsp5/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsp-006', source: 'mock',
    name: 'Pousada do Pilar',
    city: 'Recife',
    address: 'Praça Joaquim Nabuco, 51 - Santo Antônio',
    type: 'Pousada',
    rating: 4.3, reviewCount: 345,
    pricePerNight: { total: 175.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsp6/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
];

export const MOCK_HOTEL_SHOWCASE_TOP_RATED = [
  {
    id: 'hsr-001', source: 'mock',
    name: 'Copacabana Palace',
    city: 'Rio de Janeiro',
    address: 'Av. Atlântica, 1702 - Copacabana',
    type: 'Hotel',
    rating: 4.9, reviewCount: 3456,
    pricePerNight: { total: 2950.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsr1/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsr-002', source: 'mock',
    name: 'Hotel Fasano Rio de Janeiro',
    city: 'Rio de Janeiro',
    address: 'Av. Vieira Souto, 80 - Ipanema',
    type: 'Hotel',
    rating: 4.8, reviewCount: 2890,
    pricePerNight: { total: 1850.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsr2/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsr-003', source: 'mock',
    name: 'Hotel Emiliano São Paulo',
    city: 'São Paulo',
    address: 'R. Oscar Freire, 384 - Jardins',
    type: 'Hotel',
    rating: 4.8, reviewCount: 1980,
    pricePerNight: { total: 1650.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsr3/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsr-004', source: 'mock',
    name: 'Uxua Casa Hotel & Spa',
    city: 'Porto Seguro',
    address: 'Praça São João, 172 - Trancoso',
    type: 'Hotel Boutique',
    rating: 4.9, reviewCount: 1234,
    pricePerNight: { total: 2400.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsr4/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsr-005', source: 'mock',
    name: 'Palácio Tangará',
    city: 'São Paulo',
    address: 'Av. Dep. Laércio Corte, 1501 - Panamby',
    type: 'Hotel',
    rating: 4.8, reviewCount: 2100,
    pricePerNight: { total: 1980.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsr5/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsr-006', source: 'mock',
    name: 'Hotel Villa Bahia',
    city: 'Salvador',
    address: 'Largo do Cruzeiro de São Francisco, 16 - Pelourinho',
    type: 'Hotel Boutique',
    rating: 4.7, reviewCount: 1560,
    pricePerNight: { total: 890.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsr6/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
];

export const MOCK_HOTEL_SHOWCASE_UNIQUE = [
  {
    id: 'hsu-001', source: 'mock',
    name: 'Nannai Resort & Spa',
    city: 'Recife',
    address: 'Rodovia PE-009, Km 3 - Muro Alto, Ipojuca',
    type: 'Resort All-Inclusive',
    rating: 4.8, reviewCount: 2340,
    pricePerNight: { total: 1890.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsu1/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsu-002', source: 'mock',
    name: 'Pousada Maravilha',
    city: 'Fernando de Noronha',
    address: 'BR-363, s/n - Sueste',
    type: 'Pousada de Charme',
    rating: 4.9, reviewCount: 890,
    pricePerNight: { total: 3200.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsu2/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsu-003', source: 'mock',
    name: 'Hotel Santa Teresa - MGallery',
    city: 'Rio de Janeiro',
    address: 'R. Almirante Alexandrino, 660 - Santa Teresa',
    type: 'Hotel Boutique',
    rating: 4.7, reviewCount: 1678,
    pricePerNight: { total: 1250.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsu3/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsu-004', source: 'mock',
    name: 'Txai Resort Itacaré',
    city: 'Itacaré',
    address: 'Rodovia Ilhéus-Itacaré, Km 48',
    type: 'Resort',
    rating: 4.8, reviewCount: 1450,
    pricePerNight: { total: 2100.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsu4/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsu-005', source: 'mock',
    name: 'Solar do Império',
    city: 'Paraty',
    address: 'R. do Comércio, 22 - Centro Histórico',
    type: 'Hotel Histórico',
    rating: 4.6, reviewCount: 780,
    pricePerNight: { total: 650.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsu5/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'hsu-006', source: 'mock',
    name: 'Kiaroa Eco-Luxury Resort',
    city: 'Maraú',
    address: 'Península de Maraú - Praia de Taipé de Fora',
    type: 'Resort Eco-Luxury',
    rating: 4.9, reviewCount: 560,
    pricePerNight: { total: 2800.00, currency: 'BRL' },
    photoUrl: 'https://picsum.photos/seed/hsu6/800/600',
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
];

// ─── Tour Showcase ────────────────────────────────────────────────────────────
// Pre-curated data for the public tours showcase page (3 sections × 6 items)

export const MOCK_TOUR_SHOWCASE_MOST_BOOKED = [
  {
    id: 'tsb-001', source: 'mock',
    name: 'City Tour Rio: Cristo, Pão de Açúcar e Maracanã',
    description: 'Tour completo pelos principais pontos turísticos do Rio em veículo privativo.',
    city: 'Rio de Janeiro',
    durationMinutes: 480,
    rating: 4.8, reviewCount: 4560,
    price: { total: 290.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsb1a/800/600', 'https://picsum.photos/seed/tsb1b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsb-002', source: 'mock',
    name: 'Passeio de Barco pelas Ilhas de Angra dos Reis',
    description: 'Navegue por ilhas paradisíacas com paradas para mergulho e almoço a bordo.',
    city: 'Rio de Janeiro',
    durationMinutes: 540,
    rating: 4.7, reviewCount: 3280,
    price: { total: 195.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsb2a/800/600', 'https://picsum.photos/seed/tsb2b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
  {
    id: 'tsb-003', source: 'mock',
    name: 'Tour Histórico pelo Pelourinho',
    description: 'Caminhada guiada pelo centro histórico de Salvador com acarajé e música baiana.',
    city: 'Salvador',
    durationMinutes: 240,
    rating: 4.6, reviewCount: 2890,
    price: { total: 120.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsb3a/800/600', 'https://picsum.photos/seed/tsb3b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsb-004', source: 'mock',
    name: 'Cataratas do Iguaçu - Tour Completo',
    description: 'Visita aos lados brasileiro e argentino das cataratas com transporte e guia.',
    city: 'Foz do Iguaçu',
    durationMinutes: 600,
    rating: 4.9, reviewCount: 5120,
    price: { total: 350.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsb4a/800/600', 'https://picsum.photos/seed/tsb4b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsb-005', source: 'mock',
    name: 'Passeio à Praia do Sancho - Noronha',
    description: 'Trilha até a praia mais bonita do Brasil com guia ambiental certificado.',
    city: 'Fernando de Noronha',
    durationMinutes: 300,
    rating: 4.9, reviewCount: 1890,
    price: { total: 280.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsb5a/800/600', 'https://picsum.photos/seed/tsb5b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
  {
    id: 'tsb-006', source: 'mock',
    name: 'Tour de Bicicleta pela Av. Paulista',
    description: 'Pedale pela avenida mais famosa de SP com parada em museus e cafés.',
    city: 'São Paulo',
    durationMinutes: 180,
    rating: 4.5, reviewCount: 2100,
    price: { total: 89.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsb6a/800/600', 'https://picsum.photos/seed/tsb6b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
];

export const MOCK_TOUR_SHOWCASE_MUST_DO = [
  {
    id: 'tsm-001', source: 'mock',
    name: 'Subida ao Cristo Redentor de Trem',
    description: 'Suba de trem do Cosme Velho até o topo do Corcovado e veja o Rio do alto.',
    city: 'Rio de Janeiro',
    durationMinutes: 240,
    rating: 4.8, reviewCount: 6780,
    price: { total: 180.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsm1a/800/600', 'https://picsum.photos/seed/tsm1b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsm-002', source: 'mock',
    name: 'Bondinho do Pão de Açúcar',
    description: 'Vista panorâmica de 360° da Baía de Guanabara ao pôr do sol.',
    city: 'Rio de Janeiro',
    durationMinutes: 180,
    rating: 4.7, reviewCount: 5430,
    price: { total: 150.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsm2a/800/600', 'https://picsum.photos/seed/tsm2b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsm-003', source: 'mock',
    name: 'Mergulho em Fernando de Noronha',
    description: 'Batismo de mergulho com cilindro em águas cristalinas com vida marinha incrível.',
    city: 'Fernando de Noronha',
    durationMinutes: 240,
    rating: 4.9, reviewCount: 2340,
    price: { total: 450.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsm3a/800/600', 'https://picsum.photos/seed/tsm3b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
  {
    id: 'tsm-004', source: 'mock',
    name: 'Flutuação no Rio Sucuri - Bonito',
    description: 'Flutue em águas cristalinas cercado por peixes e vegetação subaquática.',
    city: 'Bonito',
    durationMinutes: 180,
    rating: 4.9, reviewCount: 3120,
    price: { total: 320.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsm4a/800/600', 'https://picsum.photos/seed/tsm4b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsm-005', source: 'mock',
    name: 'Elevador Lacerda + Mercado Modelo',
    description: 'Desça pelo icônico elevador e explore o artesanato no Mercado Modelo.',
    city: 'Salvador',
    durationMinutes: 120,
    rating: 4.5, reviewCount: 1890,
    price: { total: 65.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsm5a/800/600', 'https://picsum.photos/seed/tsm5b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
  {
    id: 'tsm-006', source: 'mock',
    name: 'Passeio de Jangada em Porto de Galinhas',
    description: 'Navegue de jangada até as piscinas naturais e nade entre peixes coloridos.',
    city: 'Recife',
    durationMinutes: 120,
    rating: 4.6, reviewCount: 4100,
    price: { total: 75.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsm6a/800/600', 'https://picsum.photos/seed/tsm6b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
];

export const MOCK_TOUR_SHOWCASE_UNIQUE = [
  {
    id: 'tsu-001', source: 'mock',
    name: 'Tour Gastronômico em Santa Teresa',
    description: 'Explore os sabores do bairro boêmio com degustações em 5 restaurantes únicos.',
    city: 'Rio de Janeiro',
    durationMinutes: 240,
    rating: 4.7, reviewCount: 1560,
    price: { total: 195.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsu1a/800/600', 'https://picsum.photos/seed/tsu1b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
  {
    id: 'tsu-002', source: 'mock',
    name: 'Aula de Culinária Baiana',
    description: 'Aprenda a fazer moqueca, acarajé e vatapá com chef local em Salvador.',
    city: 'Salvador',
    durationMinutes: 300,
    rating: 4.8, reviewCount: 890,
    price: { total: 250.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsu2a/800/600', 'https://picsum.photos/seed/tsu2b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
  {
    id: 'tsu-003', source: 'mock',
    name: 'Tour Fotográfico ao Nascer do Sol',
    description: 'Fotografe o amanhecer nos mirantes secretos do Rio com fotógrafo profissional.',
    city: 'Rio de Janeiro',
    durationMinutes: 210,
    rating: 4.9, reviewCount: 670,
    price: { total: 320.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsu3a/800/600', 'https://picsum.photos/seed/tsu3b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsu-004', source: 'mock',
    name: 'Trilha Guiada na Chapada Diamantina',
    description: 'Explore cavernas, cachoeiras e vales da Chapada com guia credenciado.',
    city: 'Chapada Diamantina',
    durationMinutes: 540,
    rating: 4.8, reviewCount: 1230,
    price: { total: 280.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsu4a/800/600', 'https://picsum.photos/seed/tsu4b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsu-005', source: 'mock',
    name: 'Passeio de Helicóptero pelo Rio',
    description: 'Voo panorâmico sobrevoando Cristo Redentor, Pão de Açúcar e praias.',
    city: 'Rio de Janeiro',
    durationMinutes: 30,
    rating: 4.8, reviewCount: 2100,
    price: { total: 590.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsu5a/800/600', 'https://picsum.photos/seed/tsu5b/800/600'],
    link: { url: 'https://www.viator.com', provider: 'Viator' },
  },
  {
    id: 'tsu-006', source: 'mock',
    name: 'Show de Samba com Jantar na Lapa',
    description: 'Noite de samba autêntico com jantar típico em casa de shows tradicional.',
    city: 'Rio de Janeiro',
    durationMinutes: 180,
    rating: 4.6, reviewCount: 1780,
    price: { total: 220.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/tsu6a/800/600', 'https://picsum.photos/seed/tsu6b/800/600'],
    link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' },
  },
];

// ─── Hotel Destinations ────────────────────────────────────────────────────────

export const MOCK_HOTEL_DESTINATIONS = [
  { destId: 'br-sp', name: 'São Paulo', label: 'São Paulo, Brasil', searchType: 'CITY' },
  { destId: 'br-rj', name: 'Rio de Janeiro', label: 'Rio de Janeiro, Brasil', searchType: 'CITY' },
  { destId: 'br-ssa', name: 'Salvador', label: 'Salvador, Bahia, Brasil', searchType: 'CITY' },
  { destId: 'br-fln', name: 'Florianópolis', label: 'Florianópolis, Brasil', searchType: 'CITY' },
  { destId: 'br-for', name: 'Fortaleza', label: 'Fortaleza, Brasil', searchType: 'CITY' },
  { destId: 'br-rec', name: 'Recife', label: 'Recife, Brasil', searchType: 'CITY' },
  { destId: 'br-cwb', name: 'Curitiba', label: 'Curitiba, Brasil', searchType: 'CITY' },
  { destId: 'br-bsb', name: 'Brasília', label: 'Brasília, Brasil', searchType: 'CITY' },
  { destId: 'br-bh', name: 'Belo Horizonte', label: 'Belo Horizonte, Brasil', searchType: 'CITY' },
  { destId: 'br-nat', name: 'Natal', label: 'Natal, Brasil', searchType: 'CITY' },
  { destId: 'br-mcz', name: 'Maceió', label: 'Maceió, Brasil', searchType: 'CITY' },
  { destId: 'br-poa', name: 'Porto Alegre', label: 'Porto Alegre, Brasil', searchType: 'CITY' },
  { destId: 'pt-lis', name: 'Lisboa', label: 'Lisboa, Portugal', searchType: 'CITY' },
  { destId: 'ar-bue', name: 'Buenos Aires', label: 'Buenos Aires, Argentina', searchType: 'CITY' },
];

// ─── Hotels/Stays ──────────────────────────────────────────────────────────────

export const MOCK_STAYS = [
  {
    id: 'ht-001', source: 'mock', addedToItinerary: false,
    name: 'Hotel Fasano Rio de Janeiro',
    location: { latitude: -22.9868, longitude: -43.1986 },
    address: 'Av. Vieira Souto, 80 - Ipanema, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 1850.00, currency: 'BRL' },
    rating: 4.8, photoUrl: 'https://picsum.photos/seed/hotel1a/800/600',
    images: ['https://picsum.photos/seed/hotel1a/800/600', 'https://picsum.photos/seed/hotel1b/800/600', 'https://picsum.photos/seed/hotel1c/800/600', 'https://picsum.photos/seed/hotel1d/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-002', source: 'mock', addedToItinerary: false,
    name: 'Copacabana Palace',
    location: { latitude: -22.9671, longitude: -43.1780 },
    address: 'Av. Atlântica, 1702 - Copacabana, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 2950.00, currency: 'BRL' },
    rating: 4.9, photoUrl: 'https://picsum.photos/seed/hotel2a/800/600',
    images: ['https://picsum.photos/seed/hotel2a/800/600', 'https://picsum.photos/seed/hotel2b/800/600', 'https://picsum.photos/seed/hotel2c/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-003', source: 'mock', addedToItinerary: false,
    name: 'Ibis Copacabana Posto 2',
    location: { latitude: -22.9660, longitude: -43.1770 },
    address: 'Rua Ministro Viveiros de Castro, 134 - Copacabana, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 320.00, currency: 'BRL' },
    rating: 3.8, photoUrl: 'https://picsum.photos/seed/hotel3a/800/600',
    images: ['https://picsum.photos/seed/hotel3a/800/600', 'https://picsum.photos/seed/hotel3b/800/600', 'https://picsum.photos/seed/hotel3c/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-004', source: 'mock', addedToItinerary: false,
    name: 'Windsor Atlantica Hotel',
    location: { latitude: -22.9670, longitude: -43.1785 },
    address: 'Av. Atlântica, 1020 - Copacabana, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 680.00, currency: 'BRL' },
    rating: 4.3, photoUrl: 'https://picsum.photos/seed/hotel4a/800/600',
    images: ['https://picsum.photos/seed/hotel4a/800/600', 'https://picsum.photos/seed/hotel4b/800/600', 'https://picsum.photos/seed/hotel4c/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-005', source: 'mock', addedToItinerary: false,
    name: 'Hotel Emiliano Rio',
    location: { latitude: -22.9844, longitude: -43.1992 },
    address: 'Av. Atlântica, 3804 - Copacabana, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 1250.00, currency: 'BRL' },
    rating: 4.6, photoUrl: 'https://picsum.photos/seed/hotel5a/800/600',
    images: ['https://picsum.photos/seed/hotel5a/800/600', 'https://picsum.photos/seed/hotel5b/800/600', 'https://picsum.photos/seed/hotel5c/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-006', source: 'mock', addedToItinerary: false,
    name: 'Selina Lapa Rio de Janeiro',
    location: { latitude: -22.9130, longitude: -43.1815 },
    address: 'R. do Riachuelo, 169 - Lapa, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 195.00, currency: 'BRL' },
    rating: 3.5, photoUrl: 'https://picsum.photos/seed/hotel6a/800/600',
    images: ['https://picsum.photos/seed/hotel6a/800/600', 'https://picsum.photos/seed/hotel6b/800/600', 'https://picsum.photos/seed/hotel6c/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-007', source: 'mock', addedToItinerary: false,
    name: 'Grand Hyatt Rio de Janeiro',
    location: { latitude: -23.0010, longitude: -43.3050 },
    address: 'Av. Lúcio Costa, 9600 - Barra da Tijuca, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 890.00, currency: 'BRL' },
    rating: 4.5, photoUrl: 'https://picsum.photos/seed/hotel7a/800/600',
    images: ['https://picsum.photos/seed/hotel7a/800/600', 'https://picsum.photos/seed/hotel7b/800/600', 'https://picsum.photos/seed/hotel7c/800/600', 'https://picsum.photos/seed/hotel7d/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
  {
    id: 'ht-008', source: 'mock', addedToItinerary: false,
    name: 'Novotel RJ Botafogo',
    location: { latitude: -22.9520, longitude: -43.1830 },
    address: 'R. Humaitá, 305 - Botafogo, Rio de Janeiro',
    checkIn: '2026-03-15', checkOut: '2026-03-18',
    pricePerNight: { total: 450.00, currency: 'BRL' },
    rating: 4.1, photoUrl: 'https://picsum.photos/seed/hotel8a/800/600',
    images: ['https://picsum.photos/seed/hotel8a/800/600', 'https://picsum.photos/seed/hotel8b/800/600', 'https://picsum.photos/seed/hotel8c/800/600'],
    link: { url: 'https://www.booking.com', provider: 'Booking.com' },
  },
];

// ─── Car Locations ─────────────────────────────────────────────────────────────

export const MOCK_CAR_LOCATIONS = [
  { id: 'cl-01', name: 'São Paulo - Guarulhos', label: 'Aeroporto de Guarulhos (GRU), São Paulo', cityId: 'sp-gru', latitude: -23.4356, longitude: -46.4731 },
  { id: 'cl-02', name: 'Rio de Janeiro - Galeão', label: 'Aeroporto do Galeão (GIG), Rio de Janeiro', cityId: 'rj-gig', latitude: -22.8100, longitude: -43.2505 },
  { id: 'cl-03', name: 'Rio de Janeiro - Santos Dumont', label: 'Aeroporto Santos Dumont (SDU), Rio de Janeiro', cityId: 'rj-sdu', latitude: -22.9104, longitude: -43.1630 },
  { id: 'cl-04', name: 'Florianópolis', label: 'Aeroporto Hercílio Luz (FLN), Florianópolis', cityId: 'fln', latitude: -27.6706, longitude: -48.5525 },
  { id: 'cl-05', name: 'Salvador', label: 'Aeroporto de Salvador (SSA), Salvador', cityId: 'ssa', latitude: -12.9111, longitude: -38.3313 },
  { id: 'cl-06', name: 'Brasília', label: 'Aeroporto de Brasília (BSB), Brasília', cityId: 'bsb', latitude: -15.8711, longitude: -47.9186 },
  { id: 'cl-07', name: 'Curitiba', label: 'Aeroporto Afonso Pena (CWB), Curitiba', cityId: 'cwb', latitude: -25.5285, longitude: -49.1758 },
  { id: 'cl-08', name: 'Belo Horizonte', label: 'Aeroporto de Confins (CNF), Belo Horizonte', cityId: 'cnf', latitude: -19.6244, longitude: -43.9720 },
];

// ─── Car Rentals ───────────────────────────────────────────────────────────────

export const MOCK_CAR_RENTALS = [
  {
    id: 'cr-001', source: 'mock', addedToItinerary: false,
    vehicleType: 'Economy',
    pickUpLocation: 'Aeroporto de Guarulhos (GRU)', dropOffLocation: 'Aeroporto de Guarulhos (GRU)',
    pickUpAt: '2026-03-15T10:00:00', dropOffAt: '2026-03-20T10:00:00',
    price: { total: 485.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/car1a/800/600', 'https://picsum.photos/seed/car1b/800/600', 'https://picsum.photos/seed/car1c/800/600'],
    link: { url: 'https://www.localiza.com', provider: 'Localiza' },
  },
  {
    id: 'cr-002', source: 'mock', addedToItinerary: false,
    vehicleType: 'Compact',
    pickUpLocation: 'Aeroporto de Guarulhos (GRU)', dropOffLocation: 'Aeroporto de Guarulhos (GRU)',
    pickUpAt: '2026-03-15T10:00:00', dropOffAt: '2026-03-20T10:00:00',
    price: { total: 620.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/car2a/800/600', 'https://picsum.photos/seed/car2b/800/600', 'https://picsum.photos/seed/car2c/800/600'],
    link: { url: 'https://www.movida.com.br', provider: 'Movida' },
  },
  {
    id: 'cr-003', source: 'mock', addedToItinerary: false,
    vehicleType: 'SUV',
    pickUpLocation: 'Aeroporto de Guarulhos (GRU)', dropOffLocation: 'Aeroporto de Guarulhos (GRU)',
    pickUpAt: '2026-03-15T10:00:00', dropOffAt: '2026-03-20T10:00:00',
    price: { total: 1150.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/car3a/800/600', 'https://picsum.photos/seed/car3b/800/600', 'https://picsum.photos/seed/car3c/800/600'],
    link: { url: 'https://www.unidas.com.br', provider: 'Unidas' },
  },
  {
    id: 'cr-004', source: 'mock', addedToItinerary: false,
    vehicleType: 'Full Size',
    pickUpLocation: 'Aeroporto de Guarulhos (GRU)', dropOffLocation: 'Aeroporto de Guarulhos (GRU)',
    pickUpAt: '2026-03-15T10:00:00', dropOffAt: '2026-03-20T10:00:00',
    price: { total: 870.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/car4a/800/600', 'https://picsum.photos/seed/car4b/800/600', 'https://picsum.photos/seed/car4c/800/600'],
    link: { url: 'https://www.localiza.com', provider: 'Localiza' },
  },
  {
    id: 'cr-005', source: 'mock', addedToItinerary: false,
    vehicleType: 'Premium',
    pickUpLocation: 'Aeroporto do Galeão (GIG)', dropOffLocation: 'Aeroporto do Galeão (GIG)',
    pickUpAt: '2026-03-15T10:00:00', dropOffAt: '2026-03-20T10:00:00',
    price: { total: 1680.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/car5a/800/600', 'https://picsum.photos/seed/car5b/800/600', 'https://picsum.photos/seed/car5c/800/600'],
    link: { url: 'https://www.movida.com.br', provider: 'Movida' },
  },
  {
    id: 'cr-006', source: 'mock', addedToItinerary: false,
    vehicleType: 'Minivan',
    pickUpLocation: 'Aeroporto do Galeão (GIG)', dropOffLocation: 'Aeroporto do Galeão (GIG)',
    pickUpAt: '2026-03-15T10:00:00', dropOffAt: '2026-03-20T10:00:00',
    price: { total: 1350.00, currency: 'BRL' },
    images: ['https://picsum.photos/seed/car6a/800/600', 'https://picsum.photos/seed/car6b/800/600', 'https://picsum.photos/seed/car6c/800/600'],
    link: { url: 'https://www.unidas.com.br', provider: 'Unidas' },
  },
];

// ─── Transport ─────────────────────────────────────────────────────────────────

export const MOCK_TRANSPORTS = [
  { id: 'tr-001', source: 'mock', addedToItinerary: false, mode: 'bus', origin: 'São Paulo', destination: 'Rio de Janeiro', departureAt: '2026-03-15T08:00:00', arrivalAt: '2026-03-15T14:30:00', durationMinutes: 390, price: { total: 120.00, currency: 'BRL' }, link: { url: 'https://www.clickbus.com.br', provider: 'ClickBus' } },
  { id: 'tr-002', source: 'mock', addedToItinerary: false, mode: 'bus', origin: 'São Paulo', destination: 'Rio de Janeiro', departureAt: '2026-03-15T23:00:00', arrivalAt: '2026-03-16T05:30:00', durationMinutes: 390, price: { total: 95.00, currency: 'BRL' }, link: { url: 'https://www.buser.com.br', provider: 'Buser' } },
  { id: 'tr-003', source: 'mock', addedToItinerary: false, mode: 'bus', origin: 'São Paulo', destination: 'Curitiba', departureAt: '2026-03-15T07:30:00', arrivalAt: '2026-03-15T13:30:00', durationMinutes: 360, price: { total: 110.00, currency: 'BRL' }, link: { url: 'https://www.clickbus.com.br', provider: 'ClickBus' } },
  { id: 'tr-004', source: 'mock', addedToItinerary: false, mode: 'train', origin: 'São Paulo', destination: 'Jundiaí', departureAt: '2026-03-15T06:00:00', arrivalAt: '2026-03-15T07:20:00', durationMinutes: 80, price: { total: 15.00, currency: 'BRL' }, link: { url: 'https://www.cptm.sp.gov.br', provider: 'CPTM' } },
  { id: 'tr-005', source: 'mock', addedToItinerary: false, mode: 'ferry', origin: 'Salvador', destination: 'Ilha de Itaparica', departureAt: '2026-03-15T09:00:00', arrivalAt: '2026-03-15T10:00:00', durationMinutes: 60, price: { total: 8.50, currency: 'BRL' }, link: { url: 'https://www.internacional.com.br', provider: 'Internacional Travessias' } },
  { id: 'tr-006', source: 'mock', addedToItinerary: false, mode: 'bus', origin: 'Rio de Janeiro', destination: 'Búzios', departureAt: '2026-03-15T08:30:00', arrivalAt: '2026-03-15T11:30:00', durationMinutes: 180, price: { total: 75.00, currency: 'BRL' }, link: { url: 'https://www.clickbus.com.br', provider: 'ClickBus' } },
];

// ─── Tours/Activities ──────────────────────────────────────────────────────────

export const MOCK_ACTIVITIES = [
  { id: 'ac-001', source: 'mock', addedToItinerary: false, name: 'Passeio de Helicóptero pelo Rio de Janeiro', description: 'Voo panorâmico sobrevoando Cristo Redentor, Pão de Açúcar e praias da Zona Sul.', location: { latitude: -22.9519, longitude: -43.2105 }, city: 'Rio de Janeiro', durationMinutes: 30, price: { total: 590.00, currency: 'BRL' }, images: ['https://picsum.photos/seed/tour1a/800/600', 'https://picsum.photos/seed/tour1b/800/600', 'https://picsum.photos/seed/tour1c/800/600'], link: { url: 'https://www.viator.com', provider: 'Viator' } },
  { id: 'ac-002', source: 'mock', addedToItinerary: false, name: 'Tour Gastronômico em Santa Teresa', description: 'Explore os sabores do bairro boêmio de Santa Teresa com degustações em 5 restaurantes.', location: { latitude: -22.9213, longitude: -43.1858 }, city: 'Rio de Janeiro', durationMinutes: 240, price: { total: 195.00, currency: 'BRL' }, images: ['https://picsum.photos/seed/tour2a/800/600', 'https://picsum.photos/seed/tour2b/800/600', 'https://picsum.photos/seed/tour2c/800/600'], link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' } },
  { id: 'ac-003', source: 'mock', addedToItinerary: false, name: 'Trilha na Floresta da Tijuca', description: 'Caminhada guiada pela maior floresta urbana do mundo, com parada em cachoeiras.', location: { latitude: -22.9537, longitude: -43.2830 }, city: 'Rio de Janeiro', durationMinutes: 300, price: { total: 140.00, currency: 'BRL' }, images: ['https://picsum.photos/seed/tour3a/800/600', 'https://picsum.photos/seed/tour3b/800/600', 'https://picsum.photos/seed/tour3c/800/600'], link: { url: 'https://www.viator.com', provider: 'Viator' } },
  { id: 'ac-004', source: 'mock', addedToItinerary: false, name: 'Aula de Surf em Copacabana', description: 'Aula particular de surf para iniciantes na praia de Copacabana com instrutor certificado.', location: { latitude: -22.9711, longitude: -43.1823 }, city: 'Rio de Janeiro', durationMinutes: 120, price: { total: 180.00, currency: 'BRL' }, images: ['https://picsum.photos/seed/tour4a/800/600', 'https://picsum.photos/seed/tour4b/800/600', 'https://picsum.photos/seed/tour4c/800/600'], link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' } },
  { id: 'ac-005', source: 'mock', addedToItinerary: false, name: 'Passeio de Escuna pela Baía de Guanabara', description: 'Navegue pela Baía de Guanabara com paradas para mergulho e vista do Pão de Açúcar.', location: { latitude: -22.9064, longitude: -43.1657 }, city: 'Rio de Janeiro', durationMinutes: 360, price: { total: 250.00, currency: 'BRL' }, images: ['https://picsum.photos/seed/tour5a/800/600', 'https://picsum.photos/seed/tour5b/800/600', 'https://picsum.photos/seed/tour5c/800/600'], link: { url: 'https://www.viator.com', provider: 'Viator' } },
  { id: 'ac-006', source: 'mock', addedToItinerary: false, name: 'Show de Samba com Jantar na Lapa', description: 'Noite de samba autêntico com jantar típico em casa de shows tradicional da Lapa.', location: { latitude: -22.9129, longitude: -43.1801 }, city: 'Rio de Janeiro', durationMinutes: 180, price: { total: 220.00, currency: 'BRL' }, images: ['https://picsum.photos/seed/tour6a/800/600', 'https://picsum.photos/seed/tour6b/800/600', 'https://picsum.photos/seed/tour6c/800/600'], link: { url: 'https://www.getyourguide.com', provider: 'GetYourGuide' } },
];

// ─── Attractions ───────────────────────────────────────────────────────────────

export const MOCK_ATTRACTIONS = [
  { id: 'at-001', source: 'mock', addedToItinerary: false, name: 'Cristo Redentor', description: 'Uma das Sete Maravilhas do Mundo Moderno, com vista panorâmica da cidade.', location: { latitude: -22.9519, longitude: -43.2105 }, city: 'Rio de Janeiro', category: 'Monumento', images: ['https://picsum.photos/seed/attr1a/800/600', 'https://picsum.photos/seed/attr1b/800/600', 'https://picsum.photos/seed/attr1c/800/600'], link: { url: 'https://www.cristoredentoroficial.com.br', provider: 'Site Oficial' } },
  { id: 'at-002', source: 'mock', addedToItinerary: false, name: 'Pão de Açúcar', description: 'Complexo de morros com bondinho aéreo e vistas espetaculares da cidade e do mar.', location: { latitude: -22.9492, longitude: -43.1545 }, city: 'Rio de Janeiro', category: 'Natureza', images: ['https://picsum.photos/seed/attr2a/800/600', 'https://picsum.photos/seed/attr2b/800/600', 'https://picsum.photos/seed/attr2c/800/600'], link: { url: 'https://www.bondinho.com.br', provider: 'Bondinho Pão de Açúcar' } },
  { id: 'at-003', source: 'mock', addedToItinerary: false, name: 'Jardim Botânico do Rio de Janeiro', description: 'Jardim histórico com mais de 6.500 espécies de plantas tropicais e subtropicais.', location: { latitude: -22.9672, longitude: -43.2249 }, city: 'Rio de Janeiro', category: 'Parque', images: ['https://picsum.photos/seed/attr3a/800/600', 'https://picsum.photos/seed/attr3b/800/600', 'https://picsum.photos/seed/attr3c/800/600'], link: { url: 'https://www.jbrj.gov.br', provider: 'Site Oficial' } },
  { id: 'at-004', source: 'mock', addedToItinerary: false, name: 'Museu do Amanhã', description: 'Museu de ciências focado no futuro, projetado por Santiago Calatrava na Praça Mauá.', location: { latitude: -22.8944, longitude: -43.1796 }, city: 'Rio de Janeiro', category: 'Museu', images: ['https://picsum.photos/seed/attr4a/800/600', 'https://picsum.photos/seed/attr4b/800/600', 'https://picsum.photos/seed/attr4c/800/600'], link: { url: 'https://www.museudoamanha.org.br', provider: 'Site Oficial' } },
  { id: 'at-005', source: 'mock', addedToItinerary: false, name: 'Escadaria Selarón', description: 'Escadaria coberta com mais de 2.000 azulejos de 60 países, obra de Jorge Selarón.', location: { latitude: -22.9155, longitude: -43.1790 }, city: 'Rio de Janeiro', category: 'Arte Pública', images: ['https://picsum.photos/seed/attr5a/800/600', 'https://picsum.photos/seed/attr5b/800/600', 'https://picsum.photos/seed/attr5c/800/600'], link: null },
  { id: 'at-006', source: 'mock', addedToItinerary: false, name: 'Maracanã', description: 'O maior estádio do Brasil e palco de momentos históricos do futebol mundial.', location: { latitude: -22.9121, longitude: -43.2302 }, city: 'Rio de Janeiro', category: 'Esporte', images: ['https://picsum.photos/seed/attr6a/800/600', 'https://picsum.photos/seed/attr6b/800/600', 'https://picsum.photos/seed/attr6c/800/600'], link: { url: 'https://www.maracana.com', provider: 'Site Oficial' } },
  { id: 'at-007', source: 'mock', addedToItinerary: false, name: 'Arcos da Lapa', description: 'Aqueduto colonial do século XVIII, cartão-postal da boêmia carioca.', location: { latitude: -22.9131, longitude: -43.1804 }, city: 'Rio de Janeiro', category: 'Histórico', images: ['https://picsum.photos/seed/attr7a/800/600', 'https://picsum.photos/seed/attr7b/800/600', 'https://picsum.photos/seed/attr7c/800/600'], link: null },
  { id: 'at-008', source: 'mock', addedToItinerary: false, name: 'Praia de Ipanema', description: 'Uma das praias mais famosas do mundo, imortalizada pela música "Garota de Ipanema".', location: { latitude: -22.9838, longitude: -43.2048 }, city: 'Rio de Janeiro', category: 'Praia', images: ['https://picsum.photos/seed/attr8a/800/600', 'https://picsum.photos/seed/attr8b/800/600', 'https://picsum.photos/seed/attr8c/800/600'], link: null },
];
