import { Injectable, signal, computed, inject, effect } from '@angular/core';
import { TripStateService } from './trip-state.service';
import { ChecklistItem } from '../models/trip.models';
import { generateChecklist } from '../utils/checklist-rules';

@Injectable({ providedIn: 'root' })
export class ChecklistService {
  private readonly tripState = inject(TripStateService);
  private readonly _items = signal<ChecklistItem[]>([]);

  readonly items = this._items.asReadonly();

  readonly progress = computed(() => {
    const all = this._items();
    const done = all.filter(i => i.isChecked).length;
    return { done, total: all.length, percentage: all.length > 0 ? Math.round((done / all.length) * 100) : 0 };
  });

  readonly overdueItems = computed(() => {
    const today = new Date().toISOString().split('T')[0];
    return this._items().filter(i => !i.isChecked && i.dueDate && i.dueDate < today);
  });

  readonly byCategory = computed(() => {
    const items = this._items();
    const groups: Record<string, ChecklistItem[]> = {};
    for (const item of items) {
      if (!groups[item.category]) groups[item.category] = [];
      groups[item.category].push(item);
    }
    return groups;
  });

  constructor() {
    // Load checklist from trip state whenever the active trip changes
    effect(() => {
      const trip = this.tripState.trip();
      const saved = trip.checklist ?? [];
      this._items.set(saved);
    });
  }

  regenerate(): void {
    const trip = this.tripState.trip();
    const updated = generateChecklist(trip, this._items());
    this._items.set(updated);
    this.persist();
  }

  toggle(id: string): void {
    this._items.update(items =>
      items.map(i => i.id === id ? { ...i, isChecked: !i.isChecked } : i)
    );
    this.persist();
  }

  addManual(item: Omit<ChecklistItem, 'id' | 'isChecked' | 'autoGenerated' | 'ruleId'>): void {
    this._items.update(items => [...items, {
      ...item,
      id: crypto.randomUUID(),
      isChecked: false,
      autoGenerated: false,
      ruleId: null,
    }]);
    this.persist();
  }

  remove(id: string): void {
    this._items.update(items => items.filter(i => i.id !== id));
    this.persist();
  }

  setItems(items: ChecklistItem[]): void {
    this._items.set(items);
    this.persist();
  }

  private persist(): void {
    this.tripState.setChecklist(this._items());
  }

  getCategoryIcon(cat: string): string {
    const map: Record<string, string> = {
      documents: 'description', health: 'favorite', packing: 'luggage',
      logistics: 'settings', finance: 'account_balance_wallet',
    };
    return map[cat] || 'checklist';
  }

  getCategoryLabel(cat: string): string {
    const map: Record<string, string> = {
      documents: 'Documentos', health: 'Saúde', packing: 'Bagagem',
      logistics: 'Logística', finance: 'Financeiro',
    };
    return map[cat] || cat;
  }
}
